# Generated by Django 2.1.5 on 2020-02-19 23:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_title', models.CharField(max_length=200)),
                ('project_content', models.TextField()),
                ('project_published', models.DateTimeField(default=datetime.datetime(2020, 2, 19, 23, 58, 26, 78556, tzinfo=utc), verbose_name='date published')),
                ('project_url', models.URLField()),
            ],
        ),
    ]
