# Generated by Django 2.1.5 on 2020-02-20 03:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200220_0328'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_image',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='project_published',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 20, 3, 32, 10, 563640, tzinfo=utc), verbose_name='date published'),
        ),
    ]
