# Generated by Django 2.1.5 on 2020-02-20 23:45

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20200220_0332'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_test_image',
            field=models.ImageField(blank=True, null=True, upload_to=None),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_published',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 20, 23, 45, 49, 428793, tzinfo=utc), verbose_name='date published'),
        ),
    ]
