# Generated by Django 2.1.5 on 2020-02-20 23:46

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20200220_2345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_published',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 20, 23, 46, 58, 163932, tzinfo=utc), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_test_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
