# Generated by Django 2.1.5 on 2020-02-21 00:10

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20200220_2346'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='project_test_image',
        ),
        migrations.AlterField(
            model_name='project',
            name='project_image',
            field=models.ImageField(blank=True, null=True, upload_to='main/static/images/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_published',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 21, 0, 10, 49, 883614, tzinfo=utc), verbose_name='date published'),
        ),
    ]
